version: '3.8'

services:
  web:
    build: .
    expose:
      - "5003" 
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  nginx:
    image: nginx:latest
    #Map the ports by  --->  host-port:container-port
    ports:
      - "8080:80"
    #The nginx.conf file from my current directory on the host and is mounted into the container at /etc/nginx/nginx.conf replacing default config
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  
volumes:
  redis-data:
    

    